from machine import Pin

class DMXConfig():
    dmx_pin = Pin((12), Pin.OUT)
    te = None #transmit emitter
    fps = 25
    
class ButtonsConfig():
    buttons = [ 
        {'pin' : 1,
         'rest' : False,
         'pull' : 'Up',
         'name' : 'room_r'},
        {'pin' : 2,
         'rest' : False,
         'pull' : 'Up',
         'name' : 'room_l'},
        {'pin' : 3,
         'rest' : False,
         'pull' : 'Up',
         'name' : 'bed_l'},    
        {'pin' : 4,
         'rest' : False,
         'pull' : 'Up',
         'name' : 'bed_m'},
        {'pin' : 5,
         'rest' : False,
         'pull' : 'Up',
         'name' : 'bed_r'},
        {'pin' : 6,
         'rest' : False,
         'pull' : 'Up',
         'name' : 'entrance'},
        {'pin' : 7,
         'rest' : False,
         'pull' : 'Up',
         'name' : 'shower'},
        {'pin' : 8,
         'rest' : False,
         'pull' : 'Up',
         'name' : 'towlet'},
        {'pin' : 9,
         'rest' : False,
         'pull' : 'Up',
         'name' : 'kicthen_l'},
        {'pin' : 10,
         'rest' : False,
         'pull' : 'Up',
         'name' : 'kitchen_r'},
        {'pin' : 11,
         'rest' : False,
         'pull' : 'Up',
         'name' : 'cabinet_l'},
        {'pin' : 13,
         'rest' : False,
         'pull' : 'Up',
         'name' : 'cabinet_r'},
        {'pin' : 14,
         'rest' : False,
         'pull' : 'Up',
         'name' : 'balcony'},
    ]